### ISSUE TITLE
Cannot open file: anti_ddos/files/check.txt

### ISSUE THREAD

**Issue by real-cereal-boy** [Sanix-Darker/AntiDDOS-system#15]
Everything works great but it gives a 500 error when your reload it more than 5 times, and it doesn't give captcha it just says Undefined when you click a little box on one side of the screen.
SO
500 ERROR = 5 Continuous Reloads
Undefined = 2-3 reloads.

**Comment by SkelletonX** [comment]
Cannot open file: anti_ddos/files/check.txt

**Comment by real-cereal-boy** [comment]
same here.

**Comment by real-cereal-boy** [comment]
seems like the developer is not online anymore

**Comment by Sanix-Darker** [comment]
@real-cereal-boy, Am actually too busy to update a lot of thing on this repo, if you can give a PR, i will merge it !
I will try to find time to resolve a lot of issues there !

**Comment by real-cereal-boy** [comment]
check.txt is there, and i ran chmod -R 777 on the directory chmoding all of it's contents

**Comment by Sanix-Darker** [comment]
If there is not a new problem about this issue, am closing it !
