### ISSUE TITLE
fopen(anti_ddos/files/check.txt): failed to open stream

### ISSUE THREAD

**Issue by J4V4SCRYPT** [Sanix-Darker/AntiDDOS-system#16]
To be honest the file variables and everything is kinda messed up. It worked on my server, but then it went crazy and I can't seem to change the path.

The god damn variables in start.php tho

**Comment by Sanix-Darker** [comment]
Hi,
Am actually too busy to update a lot of thing on this repo, if you can give
a PR, i will merge it !
I will try to find time to resolve a lot of issues there !

Best Regards!

**Comment by real-cereal-boy** [comment]
Okey I actually figured out why! 
So it turns out if you changed the folder name, then you have to change the path in start.php
then change $ad_dir to anti_ddos/files to foldername/files
thanks!

**Comment by J4V4SCRYPT** [comment]
Ok Thanks
