### ISSUE TITLE
Invalid numeric literal

### ISSUE THREAD

**Issue by glitcher32** [Sanix-Darker/AntiDDOS-system#17]
"Parse error: Invalid numeric literal in C:\xampp\htdocs\anti_ddos\files\check.txt on line 1"

Everything works fine until the number in the check.txt file goes to something like $ad_sec_query =09; and then the error happens. I noticed that this isn't a new issue and im not the first person to run into this, but it was never resolved.

I tested against DDOS and this work fantastically, but this issue stops the whole site from working.

Please fix or tell me a work around.

PHP 7.4.6 (Even though it probably doesn't matter.)

**Comment by PierTV** [comment]
same problem

> "Parse error: Invalid numeric literal in C:\xampp\htdocs\anti_ddos\files\check.txt on line 1"
> 
> Everything works fine until the number in the check.txt file goes to something like $ad_sec_query =09; and then the error happens. I noticed that this isn't a new issue and im not the first person to run into this, but it was never resolved.
> 
> I tested against DDOS and this work fantastically, but this issue stops the whole site from working.
> 
> Please fix or tell me a work around.
> 
> PHP 7.4.6 (Even though it probably doesn't matter.)

**Comment by glitcher32** [comment]
@Sanix-Darker After a day of re-testing it, the issue appears to be resolved.
