### ISSUE TITLE
check.txt error 

### ISSUE THREAD

**Issue by alishahidi** [Sanix-Darker/AntiDDOS-system#19]
Parse error: Invalid numeric literal in F:\Program Files\Ampps\www\anti_ddos\files\check.txt on line 1

into check.txt 

<?php $ad_num_query =1; $ad_sec_query =08; ?>

When this error occurs, the site will no longer load and the program will crash completely

What should I do?

**Comment by saintly2k** [comment]
unset session (and if that doesn't work, clear cookies). i can fix this error in a new pull request.
