### ISSUE TITLE
How to use .php file? cant run to my browser sir.

### ISSUE THREAD

**Issue by PutuSuhartawan** [Sanix-Darker/AntiDDOS-system#24]

**Comment by JustinBieberSierreno** [comment]
install php in your machine

if you are using apache2 use this command : 
sudo apt-get update && sudo apt-get install apache2

if you are using nginx read this : 
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04#step-4-configuring-nginx-to-use-the-php-processor

**Comment by saintly2k** [comment]
*This should be closed*
