### ISSUE TITLE
How to remove cookies and make it check every time

### ISSUE THREAD

**Issue by IdkDwij** [Sanix-Darker/AntiDDOS-system#27]
so i used this, but my friend used cookies and ddosed my site

**Comment by saintly2k** [comment]
1. nice friend you got there
2. i'll look into this. to requrie check again, you need to unset the php session (session_destroy(); unset_session();) that should do the magic for like logout pages and stuff

**Comment by IdkDwij** [comment]
Bro this is ages old :skull:

**Comment by saintly2k** [comment]
but it isn't closed so i assume it isn't fixed/implemented yet?

**Comment by IdkDwij** [comment]
ill close it
i forgot about this issue
