### ISSUE TITLE
only white screen

### ISSUE THREAD

**Issue by vpnpanelforsale** [Sanix-Darker/AntiDDOS-system#6]
I tested this on shared hosting but after the checking it only shows white screen and it doenst show my website

**Comment by Sanix-Darker** [comment]
Hi @vpnpanelforsale can you show us what you get in your screen after reloading and what is save in files/* please ?

**Comment by Sanix-Darker** [comment]
Hi @vpnpanelforsale did you finally found the problem? there was some updates on the tool, pull and test again, let me know if there is some problems please!

**Comment by Sanix-Darker** [comment]
Closing this issues due any new problems found!
