### ISSUE TITLE
My site loads on some browsers but hangs on others..

### ISSUE THREAD

**Issue by Twinky-kms** [Sanix-Darker/AntiDDOS-system#8]
The browsers it's currently hanging on and refreshing over and over again on the "Antiddos is checking..." screeen is Chrome, Firefox. But it works on Tor which is based off of firefox which is interesting. This is my first day using this application so if there is any debug you need please let me know.

**Comment by Sanix-Darker** [comment]
Hi @Twinky-kms , wow, that's looks little strange;
Of course, you're welcome for a debugging, please can you provide some screenshot from your browser's console here, they could be some error there :thinking: , Thank you for helping the maintain of this application.

**Comment by Twinky-kms** [comment]
It started working after a little more tweaking, It may of just been my browsers local cache causing it problems. If it appears again ill look more deeply and re-open an issue.
