### ISSUE TITLE
ad_sec_query - 500 Error

### ISSUE THREAD

**Issue by jackkelly-bayliss** [Sanix-Darker/AntiDDOS-system#9]
Hello,

It appears that after a certain amount of time, this value changes to a one digit number which causes a 500 error. For example, the value currently is: 
![image](https://user-images.githubusercontent.com/31831814/58374650-a505e080-7f39-11e9-9051-496788130893.png) - Upon the value being this, it causes a 500 error. Any solutions or fixes? Thank you!

Kind Regards,
Jack

**Comment by Sanix-Darker** [comment]
Hi there, really sorry for this delay, too much things to do!
i will take time to look this issue by now!

**Comment by Sanix-Darker** [comment]
Are you still getting this error ? if yes, just tell me, i will re-open the issue !
